apiVersion: v1
kind: ConfigMap
metadata:
  name: tourismo-config
  namespace: tourismo
data:
  DEBUG: "False"
  ALLOWED_HOSTS: "tourismo.clcdream.com"
  DB_ENGINE: "postgresql"
  DB_NAME: "tourismo"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  GUNICORN_WORKERS: "3"
